siguel:	siguel.o Cidade.o Lista.o Circulo.o Retangulo.o Quadra.o Hidrante.o Semaforo.o Torre.o Procedimentos.o Operacoes_de_String.o Arquivo.o Calculos.o Processamentos.o
	gcc -o siguel siguel.o Cidade.o Lista.o Circulo.o Retangulo.o Quadra.o Hidrante.o Semaforo.o Torre.o Procedimentos.o Operacoes_de_String.o Arquivo.o Calculos.o Processamentos.o -lm

siguel.o:	siguel.c
	gcc -o siguel.o -c siguel.c -g -pedantic -ansi

Cidade.o:	Cidade.c Cidade.h
	gcc -o Cidade.o -c Cidade.c -g -pedantic -ansi

Lista.o:	Lista.c Lista.h
	gcc -o Lista.o -c Lista.c -g -pedantic -ansi

Circulo.o:	Circulo.c Circulo.h
	gcc -o Circulo.o -c Circulo.c -g -pedantic -ansi

Retangulo.o:	Retangulo.c Retangulo.h
	gcc -o Retangulo.o -c Retangulo.c -g -pedantic -ansi

Quadra.o:	Quadra.c Quadra.h
	gcc -o Quadra.o -c Quadra.c -g -pedantic -ansi

Hidrante.o:	Hidrante.c Hidrante.h
	gcc -o Hidrante.o -c Hidrante.c -g -pedantic -ansi

Semaforo.o:	Semaforo.c Semaforo.h
	gcc -o Semaforo.o -c Semaforo.c -g -pedantic -ansi

Torre.o:	Torre.c Torre.h
	gcc -o Torre.o -c Torre.c -g -pedantic -ansi

Procedimentos.o:	Procedimentos.c Procedimentos.h
	gcc -o Procedimentos.o -c Procedimentos.c -g -pedantic -ansi

Operacoes_de_String.o:	Operacoes_de_String.c Operacoes_de_String.h
	gcc -o Operacoes_de_String.o -c Operacoes_de_String.c -g -pedantic -ansi

Arquivo.o:	Arquivo.c Arquivo.h
	gcc -o Arquivo.o -c Arquivo.c -g -pedantic -ansi

Calculos.o:	Calculos.c Calculos.h
	gcc -o Calculos.o -c Calculos.c -g -pedantic -ansi

Processamentos.o:	Processamentos.c Processamentos.h
	gcc -o Processamentos.o -c Processamentos.c -g -pedantic -ansi

clear:
	rm -rf *.o *txt vgcore* siguel
